name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1.5.0
      with:
        elixir-version: '1.11.4'
        otp-version: '23.2.7.1'
    - name: Run Tests
      run: mix test
